### ISSUE TITLE
Python 3 print statements

### ISSUE THREAD

**Issue by AmandaDepoian** [mattbellis/CoGeNT_analysis_code#3]
I made changes to the following files to make them compatible with python3:

changed print statements to have ( ) in:

chris_kelso_code.py
cogent_pdfs.py
cogent_utilities.py
fitting_utilities.py
fit_rise_times_pulser.py
fit_rise_times_of_data_using_pulser_fit_inputs.py
fit_cogent_data.py
plotting_utilities.py

-----------------------------------------------------------------------
changing xrange to range in:
 
fit_cogent_data.py

**Comment by mattbellis** [comment]
So is this Issue resolved now? Should the issue be "Python 3 print statements" and then we can mark as "Resolved"?
